# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: what-why-how
author: Amit Kulkarni
# email: 
description: >- # this means to ignore newlines until "baseurl:"
  101, Security, Science, Network, Operating System, UNIX, tools, Open source, Github, Questions, How-to, Jekyll, Opinions, Thoughts, Answers, and more...
baseurl: "/whatwhyhow" # the subpath of your site, e.g. /blog
url: "https://kulkarniamit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
#rss: RSS
github_username:  kulkarniamit
github_repo: whatwhyhow

google_analytics: UA-136227765-1

# Build settings
markdown: kramdown
kramdown:
        input: GFM
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
encoding: UTF-8

feed:
  collections:
    - security
    - one-zero-one
    - howto

collections_dir: collections
collections:
  one-zero-one:
          title: "101"
          output: true
          sequence: 1
  howto:
          title: "How to"
          output: true
          sequence: 2
#  attack:
#          title: "Attacks"
#          output: true
#          sequence: 3
#  random:
#          title: "Random"
#          output: true
#          sequence: 4
  security:
          title: "Security"
          output: true
          sequence: 5

defaults:
  - scope:
      path: ""
      type: "one-zero-one"
    values:
      layout: "post"
      is_collection: true
  - scope:
      path: ""
      type: "howto"
    values:
      layout: "post"
      is_collection: true
  - scope:
      path: ""
      type: "attack"
    values:
      layout: "post"
      is_collection: true
  - scope:
      path: ""
      type: "random"
    values:
      layout: "post"
      is_collection: true
  - scope:
      path: ""
      type: "security"
    values:
      layout: "post"
      is_collection: true


#sass:
#  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
